### PR TITLE
Make sure we don't start sending data before we got vector clock

### LINKED ISSUE #50: Race condition between getVectorClock and EBT duplex streams
In `index.js`, there is `ebt.state.clock` which is vital piece of state needed for calculating what msgs are missing. This state is initialized with a simple placeholder, but it should **not** be relied upon before `getVectorClock` has responded. The current code is vulnerable to that race condition.

We should postpone the duplex streams being plugged together until `getVectorClock` is done. There are two parts to patch: the initiator duplex (`isClient=true`) and the receiving duplex. We could maybe use a pull-stream operator to intercept the plugging and do the waiting there.

cc @arj03

### PR DESCRIPTION
**Pull request by arj03**
This should fix #50. 

I have verified that this fixes the problem for me in browser-core through the power of console.log.

### CODE REVIEW

**Comment by staltz** [comment]
Good! I was hoping that this one would have a test. It's such a sneaky race condition that it's worth making sure

**Comment by arj03** [comment]
Right, can do a test

**Review by staltz — APPROVED** [review]
Tested locally that it works :+1:

**Comment by arj03** [comment]
whooop

**Pull request merged**
