### PR TITLE
Replication limiter

### PR DESCRIPTION
**Pull request by pietgeursen**
## Motivation:

[manyverse](https://github.com/staltz/manyverse) needs the ability to limit the number or peers being replicated to improve performance of the app. This PR integrates the [ssb-replication-limiter](https://github.com/ssbc/ssb-replication-limiter) module I've written to help solve that problem.

## Changes in this PR:

- adds a helper function `getPeerAheadBy` that the limiter can use to find out how far ahead a remote peer's feed is. The limiter uses this value to decide whether or not to change modes.
- change the `request` method from `ebt.request (feedId, enableReplication)` to `ebt.request (feedId, enableReplication, [priority])` so the limiter can prioritise who to replicate first. See [this PR](https://github.com/ssbc/ssb-friends/pull/11) for the changes to ssb-friends.
- adds and passes CI tests.
- exports the `request` function from the module. This wasn't done previously, I assume this was a bug because currently we're hooking the `sbot.request` function and it hasn't been needed.
- exposes methods to dynamically configure the limiter's threshold and maxNumConnections.
- uses config to set initial values for threshold and maxNumConnections

## Using `request(<feedId>, **false**)` to pause replication.

Dominic said that using request like this might cause problems with eventual consistency. See [this issue](https://github.com/dominictarr/epidemic-broadcast-trees/issues/21) for more context.

Until ebt has a better pause feature I'm hoping we can use `request` like this.

### CODE REVIEW

**Comment by mmckegg** [comment]
About to start using this branch in Patchwork. I'll let ya'll know how it goes.

**Comment by mmckegg** [comment]
sorry @pietgeursen, made a bit of a mess of the commit history trying to get master merged in (and the merge conflicts properly resolved).

**Comment by christianbundy** [comment]
Anything I can do to help this along, or are you waiting from feedback from @staltz and @dominictarr?

**Comment by staltz** [comment]
I think this is part of a project that was cancelled, so I'm not sure that this code in this state is currently reflecting a fully functional code state that we want to include into master branch. I'm inclined to *archiving* this PR for future reference once we resume this work.

**Comment by christianbundy** [comment]
Cool, I would love to merge these improvements but if the PR isn't going to get merged then I'd prefer to just close it. I'm going to close both this and https://github.com/ssbc/ssb-friends/pull/11, please re-open and/or ping me if I've done something rude/wrong.

:heart:

**Comment by dominictarr** [comment]
if I recall correctly, this was intended to fix a problem with cpu usage, or slow syncing, but once it was ready it turned out it wasn't the problem - the problem was indexing.

**Pull request closed without merging**
