### PR TITLE
change peerStatus to async to avoid error, add more careful checks on clock obj

### PR DESCRIPTION
**Pull request by mixmix**
see this issue : https://github.com/ssbc/ssb-ebt/issues/10

problem with muxrpc throwing an error about not being given a callback on a sync function D:

also some better checks to avoid "can't find @ye+4.... on null" type errors from trying to dig into a non-existent object

cc @dominictarr

### CODE REVIEW

**Comment by dominictarr** [comment]
even if it is sync, you still have to provide a cb if it's remote, but it allows you to call it locally without a callback.

**Comment by mixmix** [comment]
oh, that's unexpected ... is this a muxrpc pattern? I guess that makes sense in a way, but then it's technically async isn't it?

So your reply is informative but it doesn't 100% clarify any direction for this PR / issue. Can I guess you're proposing : 
- [x] revert async to sync
  - leave a note about how to use remote `sync` requests somewhere
- [x] keep the better checks on clock obj
- [x] keep the removal of a dead method from the manifest

???

**Comment by dominictarr** [comment]
yes this is a muxrpc pattern. it's sync on the server side, but because anything that goes from the client to the server is async, if it's called from the client it's async.

There are other a number of other sync methods such as `whoami`, `getAddress`, `query.explain`.

my suggestion is to use a callback as per the docs

**Comment by mixmix** [comment]
Cool, didn't know about that pattern, had assumed the docs were wrong in
calling it sync. That it's async makes sense. I think it would be less
confusing if all methods were just async or source, because caking methods
in the server isn't that common... And if you are (eg in a plugin) having
the same method behavior would feel more cohorent (this is some of the
point of rpc pattern right?)

**Comment by dominictarr** [comment]
some of those methods are sync because they are primarily to be called locally, but are sometimes useful to call remotely (or for debugging)... It's in the docs because the manifest is generated from the docs (that goes way back... I think i suggested that in part to try and get paul to write docs (successfully))

**Pull request closed without merging**
